---
- hosts: all
  become: true
  vars:
    ansible_become_pass: edureka
 
  tasks:
  - name: install ntp
    apt:
      pkg: ntp
      state: present
    notify:
      - run update
       
  - name: install vim
    apt:
      pkg: vim
      state: present
 
  - name: start ntp service
    service:
      name: ntp
      state: started
      enabled: true
    
  handlers:
  - name: run update
    apt:
      update_cache: yes
